### ISSUE TITLE
Cannot build in Windows using Visual Studio 2015

### ISSUE THREAD

**Issue by byouness** [OpenSourceRisk/Engine#118]
Hello,

Building ORE (QuantExt lib specifically) fails for me with a bunch of errors, listed below:

Here is my setup:

- Windows 10
- Visual C++ 14 (Visual Studio 2015)
- Boost 1.70.0
- QuantLib 1.27.1
- ORE v1.8.7.0 (tried also using the master branch)

Any idea what I am doing wrong?

Thanks in advance for your help!

1. cpicoupon.cpp
```
> QuantExt\qle/cashflows/cpicoupon.hpp(61): error C2664: 'QuantLib::CPICoupon::CPICoupon(QuantLib::CPICoupon &&)': cannot convert argument 3 from 'const QuantLib::Date' to 'QuantLib::Real' (compiling source file qle\cashflows\cpicoupon.cpp)
> QuantExt\qle/cashflows/cpicoupon.hpp(61): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called (compiling source file qle\cashflows\cpicoupon.cpp)
> qle\cashflows\cpicoupon.cpp(74): error C2039: 'baseDate': is not a member of 'QuantExt::CPICoupon'
```
2. durationadjustedcmscoupon.cpp
```
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(112): error C3668: 'QuantExt::CappedFlooredAverageONIndexedCoupon::performCalculations': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\averageonindexedcoupon.cpp)
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(112): error C3668: 'QuantExt::CappedFlooredAverageONIndexedCoupon::performCalculations': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\couponpricer.cpp)
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(112): error C3668: 'QuantExt::CappedFlooredAverageONIndexedCoupon::performCalculations': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\averageonindexedcouponpricer.cpp)
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(113): error C3668: 'QuantExt::CappedFlooredAverageONIndexedCoupon::alwaysForwardNotifications': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\averageonindexedcoupon.cpp)
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(113): error C3668: 'QuantExt::CappedFlooredAverageONIndexedCoupon::alwaysForwardNotifications': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\couponpricer.cpp)
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(113): error C3668: 'QuantExt::CappedFlooredAverageONIndexedCoupon::alwaysForwardNotifications': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\averageonindexedcouponpricer.cpp)
> QuantExt\qle/cashflows/overnightindexedcoupon.hpp(166): error C3668: 'QuantExt::CappedFlooredOvernightIndexedCoupon::performCalculations': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\brlcdicouponpricer.cpp)
> QuantExt\qle/cashflows/overnightindexedcoupon.hpp(167): error C3668: 'QuantExt::CappedFlooredOvernightIndexedCoupon::alwaysForwardNotifications': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\brlcdicouponpricer.cpp)
> QuantExt\qle/cashflows/overnightindexedcoupon.hpp(166): error C3668: 'QuantExt::CappedFlooredOvernightIndexedCoupon::performCalculations': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\couponpricer.cpp)
> QuantExt\qle/cashflows/overnightindexedcoupon.hpp(167): error C3668: 'QuantExt::CappedFlooredOvernightIndexedCoupon::alwaysForwardNotifications': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\couponpricer.cpp)
> qle\cashflows\averageonindexedcoupon.cpp(148): error C2352: 'QuantLib::LazyObject::alwaysForwardNotifications': illegal call of non-static member function QuantLib\ql/patterns/lazyobject.hpp(158): note: see declaration of 'QuantLib::LazyObject::alwaysForwardNotifications'
> qle\cashflows\averageonindexedcoupon.cpp(149): error C2039: 'alwaysForwardNotifications': is not a member of 'QuantExt::AverageONIndexedCoupon'
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(48): note: see declaration of 'QuantExt::AverageONIndexedCoupon'
> qle\cashflows\averageonindexedcoupon.cpp(168): error C2065: 'rate_': undeclared identifier
> qle\cashflows\averageonindexedcoupon.cpp(176): error C3861: 'calculate': identifier not found  durationadjustedcmscoupontsrpricer.cpp
> qle\cashflows\averageonindexedcoupon.cpp(177): error C2065: 'rate_': undeclared identifier
> qle\cashflows\averageonindexedcoupon.cpp(254): error C2039: 'alwaysForwardNotifications': is not a member of QuantExt::AverageONIndexedCoupon'
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(48): note: see declaration of 'QuantExt::AverageONIndexedCoupon'
qle\cashflows\averageonindexedcoupon.cpp(420): error C3861: 'WeekendsOnly': identifier not found
```
3. strippedcapflooredcpicoupon.cpp
``` 
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(112): error C3668: 'QuantExt::CappedFlooredAverageONIndexedCoupon::performCalculations': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\blackovernightindexedcouponpricer.cpp)
> QuantExt\qle/cashflows/averageonindexedcoupon.hpp(113): error C3668: 'QuantExt::CappedFlooredAverageONIndexedCoupon::alwaysForwardNotifications': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\blackovernightindexedcouponpricer.cpp)
> QuantExt\qle/cashflows/overnightindexedcoupon.hpp(166): error C3668: 'QuantExt::CappedFlooredOvernightIndexedCoupon::performCalculations': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\blackovernightindexedcouponpricer.cpp)
> QuantExt\qle/cashflows/overnightindexedcoupon.hpp(167): error C3668: 'QuantExt::CappedFlooredOvernightIndexedCoupon::alwaysForwardNotifications': method with override specifier 'override' did not override any base class methods (compiling source file qle\cashflows\blackovernightindexedcouponpricer.cpp)
```
4. zerofixedcoupon.cpp
``` 
>  QuantExt\qle/cashflows/cpicoupon.hpp(61): error C2664: 'QuantLib::CPICoupon::CPICoupon(QuantLib::CPICoupon &&)': cannot convert argument 3 from 'const QuantLib::Date' to 'QuantLib::Real' (compiling source file qle\cashflows\strippedcapflooredcpicoupon.cpp)
>  QuantExt\qle/cashflows/cpicoupon.hpp(61): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called (compiling source file qle\cashflows\strippedcapflooredcpicoupon.cpp)
```

**Comment by rjabrazko** [comment]
Hello Youness, 

I have the same problem same errors in VS 2019 after building Quantlib 
Did you manage to fix it?

Thanks

**Comment by rkapl123** [comment]
It looks like your Quantlib isn't the right version.
Can you confirm that 
a) in your Additional Include Directories of the QuantExt project the entry contains ..\QuantLib and
b) the version.hpp in that folder contains
```cplusplus
//! version string
#define QL_VERSION "1.27.1"

//! version hexadecimal number
#define QL_HEX_VERSION 0x012701f0
```
Unfortunately the submodule update of the quantlib folder doesn't work because of missing access rights: `fatal: clone of 'git@github.com:OpenSourceRisk/QuantLib.git' into submodule path `, so I directly downloaded a zip file from the subproject and copied into that folder. Maybe there is someone familiar enough with githubs security settings to clarify that?

**Comment by byouness** [comment]
Hello Roland,

The answer to both your questions is yes:
a) Additional Include Directories contains the following: ` .;..\QuantLib;%(AdditionalIncludeDirectories)`
b) Under `..\QuantLib\ql` the `version.hpp` file contains the right `QL_HEX_VERSION` and `QL_HEX_VERSION`.

In fact, the issues are limited to only qle/cashflows/cpicoupon and qle/cashflows/averageonindexedcoupon.

I encountered the issue when updating the submodule, so what I had done also is downlowd QuantLib and put it in the right folder.

Any other ideas what might be wrong here?

Thank you for your help with this!
Best

**Comment by byouness** [comment]
Hello @rjabrazko,

Unfortunately I still didn't manage to build QuantExt. I hope Roland or another one of ORE contributors can help us.

Best

**Comment by rkapl123** [comment]
Well, I still think you're using the wrong version of quantlib, maybe it's related to the fact that ORE uses a patched version of Quantlib. If you take a look at [cpicoupon.hpp](https://github.com/OpenSourceRisk/QuantLib/blob/49108fc15756826282da2b57648e9b5744d630c6/ql/cashflows/cpicoupon.hpp) from the current master, then you see, that there is no baseDate method in the CpiCoupon Class.

I'd suggest you download the ORE Quantlib directly from [submodule](https://github.com/OpenSourceRisk/QuantLib/tree/49108fc15756826282da2b57648e9b5744d630c6) that should fix the issue.
Or you try to git update the submodule again, if that works for you.

-regards,
Roland

**Comment by byouness** [comment]
Hi Peter, Roland,

Thanks for your replies. I didn't realise that ORE relied on a patched QuantLib. Taking QuantLib from [here](https://github.com/OpenSourceRisk/QuantLib/tree/49108fc15756826282da2b57648e9b5744d630c6) instead of the latest release fixed the problem indeed. So, I will close this issue. I still have a question though, let's say I want to build ORE release v1.8.6.1 for example, how do I know what is the compatible QuantLib release or commit?

With regards to the `git submodule update` command, even after reflecting the suggested change in .gitmodules the command still fails (I use HTTPS indeed). However, this is fine, I was planning to switch to SSH soon anyway.

Best regards,
Youness

**Comment by pcaspers** [comment]
I think you have to change `.gitmodules` before you do `git submodule init`. Each version of ORE contains the git hash of the ql submodule, so that `git submodule update` will check out the ql version that is consistent with ORE. You can also see the git hash in the code browser on GitHub or do `git ls-tree master ore/QuantLib` to get it from the root directory.

**Comment by byouness** [comment]
Crystal clear, thank you!
